# Generated by Django 6.0.7 on 2026-07-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_orderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=10),
            preserve_default=False,
        ),
    ]
